version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8080
    environment:
      - PYTHONUNBUFFERED=1
      - POETRY_VIRTUALENVS_CREATE=false
    ports:
      - "8000:8080"