# Generated by Django 5.2 on 2025-05-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'permissions': [('can_create_product', 'Can create product')]},
        ),
    ]
