# Generated by Django 5.2.1 on 2025-06-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'permissions': [('can_create_product', 'Can create product')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
